config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-em-validation:
      branch: SQAaaS
      repo: https://github.com/I2PC/scipion-em-validation
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-em-validation git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-celadon-ladybird.sh
        container: qc.acc_stealthy-champagne-pig
  QC.Doc:
    repos:
      github.com/I2PC/scipion-em-validation find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-seashell-wasp.sh
        container: qc.doc_paltry-orange-seahorse
      github.com/I2PC/scipion-em-validation git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-cardinal-monkey.sh
        container: qc.doc_paltry-tomato-beaver
      github.com/I2PC/scipion-em-validation markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-celadon-alligator.sh
        container: qc.doc_ugly-gold-albatross
  QC.Lic:
    repos:
      github.com/I2PC/scipion-em-validation licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-orchid-dodo.sh
        container: qc.lic_slaphappy-russet-falcon
  QC.Met:
    repos:
      github.com/I2PC/scipion-em-validation cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-myrtle-flamingo.sh
        container: qc.met_lovely-olive-tang
  QC.Sec:
    repos:
      github.com/I2PC/scipion-em-validation bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-lemon-newfoundland.sh
        container: qc.sec_whiny-green-gopher
  QC.Sty:
    repos:
      github.com/I2PC/scipion-em-validation flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-copper-dog.sh
        container: qc.sty_messy-lilac-chinchilla
  QC.Ver:
    repos:
      github.com/I2PC/scipion-em-validation get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-green-oriole.sh
        container: qc.ver_zippy-coral-ostrich
timeout: 1800
