config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-em-validation:
      branch: SQAaaS
      repo: https://github.com/I2PC/scipion-em-validation
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-em-validation git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-firebrick-dane.sh
        container: qc.acc_cozy-blue-vole
  QC.Doc:
    repos:
      github.com/I2PC/scipion-em-validation find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-myrtle-tzu.sh
        container: qc.doc_sleazy-cyan-gorilla
      github.com/I2PC/scipion-em-validation git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-goldenrod-uguisu.sh
        container: qc.doc_lumpy-chestnut-devil
      github.com/I2PC/scipion-em-validation markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-saffron-bobcat.sh
        container: qc.doc_hilly-khaki-wasp
  QC.Lic:
    repos:
      github.com/I2PC/scipion-em-validation licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-vermilion-wombat.sh
        container: qc.lic_stinky-gamboge-chameleon
  QC.Met:
    repos:
      github.com/I2PC/scipion-em-validation cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-rose-snail.sh
        container: qc.met_squirrely-rust-dhole
  QC.Sec:
    repos:
      github.com/I2PC/scipion-em-validation bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-pumpkin-setter.sh
        container: qc.sec_breezy-maroon-sparrow
  QC.Sty:
    repos:
      github.com/I2PC/scipion-em-validation flake8:
        commands:
        - /usr/bin/env sh .sqa/script.surly-scarlet-seahorse.sh
        container: qc.sty_nippy-harlequin-lobster
  QC.Ver:
    repos:
      github.com/I2PC/scipion-em-validation get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-periwinkle-coral.sh
        container: qc.ver_nerdy-razzmatazz-mouse
timeout: 1800
