config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-em-validation:
      branch: SQAaaS
      repo: https://github.com/I2PC/scipion-em-validation
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-em-validation git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-salmon-toucan.sh
        container: qc.acc_skinny-chocolate-affenpinscher
  QC.Doc:
    repos:
      github.com/I2PC/scipion-em-validation find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-magnolia-frigatebird.sh
        container: qc.doc_tasty-flax-retriever
      github.com/I2PC/scipion-em-validation git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-fuchsia-cassowary.sh
        container: qc.doc_lovely-firebrick-kudu
      github.com/I2PC/scipion-em-validation markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-rose-lion.sh
        container: qc.doc_goopy-wisteria-cuscus
  QC.Lic:
    repos:
      github.com/I2PC/scipion-em-validation licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-charcoal-snake.sh
        container: qc.lic_boozy-magenta-squirrel
  QC.Met:
    repos:
      github.com/I2PC/scipion-em-validation cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-violet-whippet.sh
        container: qc.met_wheezy-myrtle-stoat
  QC.Sec:
    repos:
      github.com/I2PC/scipion-em-validation bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-vermilion-schnauzer.sh
        container: qc.sec_sunny-khaki-meerkat
  QC.Sty:
    repos:
      github.com/I2PC/scipion-em-validation flake8:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-cobalt-rhinoceros.sh
        container: qc.sty_slimy-rust-warthog
  QC.Ver:
    repos:
      github.com/I2PC/scipion-em-validation get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-gold-newfoundland.sh
        container: qc.ver_gimpy-magnolia-rat
timeout: 1800
