config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-em-validation:
      branch: SQAaaS
      repo: https://github.com/I2PC/scipion-em-validation
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-em-validation git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-persimmon-crane.sh
        container: qc.acc_fuzzy-auburn-grouse
  QC.Doc:
    repos:
      github.com/I2PC/scipion-em-validation find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-orange-fossa.sh
        container: qc.doc_crabby-alizarin-woodlouse
      github.com/I2PC/scipion-em-validation git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-corn-tzu.sh
        container: qc.doc_stuffy-corn-wolf
      github.com/I2PC/scipion-em-validation markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-champagne-rat.sh
        container: qc.doc_skinny-ultramarine-barnacle
  QC.Lic:
    repos:
      github.com/I2PC/scipion-em-validation licensee:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-orange-catfish.sh
        container: qc.lic_boozy-pear-ostrich
  QC.Met:
    repos:
      github.com/I2PC/scipion-em-validation cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-azure-woodpecker.sh
        container: qc.met_flimsy-copper-snail
  QC.Sec:
    repos:
      github.com/I2PC/scipion-em-validation bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-wheat-rattlesnake.sh
        container: qc.sec_beady-cobalt-budgerigar
  QC.Sty:
    repos:
      github.com/I2PC/scipion-em-validation flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-scarlet-sparrow.sh
        container: qc.sty_stuffy-plum-swan
  QC.Ver:
    repos:
      github.com/I2PC/scipion-em-validation get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-puce-zebu.sh
        container: qc.ver_droopy-indigo-husky
timeout: 1800
