config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-em-validation:
      branch: SQAaaS
      repo: https://github.com/I2PC/scipion-em-validation
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-em-validation git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-orange-retriever.sh
        container: qc.acc_snappy-mauve-donkey
  QC.Doc:
    repos:
      github.com/I2PC/scipion-em-validation find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-eggplant-meerkat.sh
        container: qc.doc_silly-amethyst-crab
      github.com/I2PC/scipion-em-validation git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-yellow-numbat.sh
        container: qc.doc_tasty-sapphire-gopher
      github.com/I2PC/scipion-em-validation markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-ivory-penguin.sh
        container: qc.doc_blurry-gold-pig
  QC.Lic:
    repos:
      github.com/I2PC/scipion-em-validation licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-jade-havanese.sh
        container: qc.lic_leaky-dandelion-camel
  QC.Met:
    repos:
      github.com/I2PC/scipion-em-validation cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-myrtle-wolf.sh
        container: qc.met_goopy-buff-capybara
  QC.Sec:
    repos:
      github.com/I2PC/scipion-em-validation bandit:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-puce-dalmatian.sh
        container: qc.sec_squirrely-cinnabar-chipmunk
  QC.Sty:
    repos:
      github.com/I2PC/scipion-em-validation flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-indigo-angora.sh
        container: qc.sty_wimpy-vermilion-bobcat
  QC.Ver:
    repos:
      github.com/I2PC/scipion-em-validation get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-puce-akbash.sh
        container: qc.ver_wiggy-alizarin-turtle
timeout: 1800
