config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/I2PC/scipion-em-validation:
      branch: SQAaaS
      repo: https://github.com/I2PC/scipion-em-validation
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/I2PC/scipion-em-validation git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-peach-oyster.sh
        container: qc.acc_ready-alizarin-tarsier
  QC.Doc:
    repos:
      github.com/I2PC/scipion-em-validation find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-amber-liger.sh
        container: qc.doc_frumpy-thistle-cow
      github.com/I2PC/scipion-em-validation git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-ecru-albatross.sh
        container: qc.doc_randy-amethyst-beagle
      github.com/I2PC/scipion-em-validation markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-chartreuse-dormouse.sh
        container: qc.doc_snappy-seashell-tuatara
  QC.Lic:
    repos:
      github.com/I2PC/scipion-em-validation licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-fuchsia-meerkat.sh
        container: qc.lic_lousy-seashell-llama
  QC.Met:
    repos:
      github.com/I2PC/scipion-em-validation cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-teal-shrimp.sh
        container: qc.met_wiggy-asparagus-chin
  QC.Sec:
    repos:
      github.com/I2PC/scipion-em-validation bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-ecru-tang.sh
        container: qc.sec_hasty-platinum-wolverine
  QC.Sty:
    repos:
      github.com/I2PC/scipion-em-validation flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-saffron-whale.sh
        container: qc.sty_gloppy-eggplant-wolfhound
  QC.Ver:
    repos:
      github.com/I2PC/scipion-em-validation get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-platinum-albatross.sh
        container: qc.ver_hazy-gamboge-whippet
timeout: 1800
